versions:
  # renovate: datasource=github-releases depName="sharkdp/bat"
  bat: v0.25.0
  # renovate: datasource=github-releases depName="sigstore/cosign"
  cosign: v2.5.0
  # renovate: datasource=github-releases depName="wagoodman/dive"
  dive: 0.13.1
  # renovate: datasource=github-releases depName="sharkdp/fd"
  fd: v10.2.0
  # renovate: datasource=github-releases depName="junegunn/fzf"
  fzf: v0.62.0
  # renovate: datasource=github-releases depName="hairyhenderson/gomplate"
  gomplate: 4.3.2
  # renovate: datasource=github-releases depName="goreleaser/goreleaser"
  goreleaser: v2.12.7
  # renovate: datasource=github-releases depName="hadolint/hadolint"
  hadolint: v2.12.0
  # renovate: datasource=github-releases depName="jesseduffield/lazydocker"
  lazydocker: 0.24.2
  # renovate: datasource=github-releases depName="jesseduffield/lazygit"
  lazygit: 0.55.1
  # renovate: datasource=github-releases depName="cantino/mcfly"
  mcfly: v0.9.3
  # renovate: datasource=github-releases depName="restic/restic"
  restic: 0.18.1
  # renovate: datasource=github-releases depName="BurntSushi/ripgrep"
  rg: 14.1.1
  # renovate: datasource=github-releases depName="go-task/task"
  task: v3.45.4
  # renovate: datasource=github-releases depName="mikefarah/yq"
  yq: v4.45.4
  # renovate: datasource=github-releases depName="ajeetdsouza/zoxide"
  zoxide: 0.9.8
  # renovate: datasource=github-releases depName="cjbassi/ytop"
  ytop: 0.6.2

download_urls:
  bat: https://github.com/sharkdp/bat/releases/download/{{ versions.bat }}/bat-{{ versions.bat }}-i686-unknown-linux-musl.tar.gz
  cosign: https://github.com/sigstore/cosign/releases/download/{{ versions.cosign }}/cosign-linux-amd64
  dive: https://github.com/wagoodman/dive/releases/download/v{{ versions.dive }}/dive_{{ versions.dive }}_linux_amd64.tar.gz
  fd: https://github.com/sharkdp/fd/releases/download/{{ versions.fd }}/fd-{{ versions.fd }}-x86_64-unknown-linux-musl.tar.gz
  fzf: https://github.com/junegunn/fzf/releases/download/{{ versions.fzf }}/fzf-{{ versions.fzf | regex_replace('^v', '') }}-linux_amd64.tar.gz
  gomplate: https://github.com/hairyhenderson/gomplate/releases/download/v{{ versions.gomplate }}/gomplate_{{ versions.gomplate }}_linux-amd64
  goreleaser: https://github.com/goreleaser/goreleaser/releases/download/{{ versions.goreleaser }}/goreleaser_Linux_x86_64.tar.gz
  hadolint: https://github.com/hadolint/hadolint/releases/download/{{ versions.hadolint }}/hadolint-Linux-x86_64
  lazydocker: https://github.com/jesseduffield/lazydocker/releases/download/v{{ versions.lazydocker }}/lazydocker_{{ versions.lazydocker }}_Linux_x86_64.tar.gz
  lazygit: https://github.com/jesseduffield/lazygit/releases/download/v{{ versions.lazygit }}/lazygit_{{ versions.lazygit }}_Linux_x86_64.tar.gz
  mcfly: https://github.com/cantino/mcfly/releases/download/{{ versions.mcfly }}/mcfly-{{ versions.mcfly }}-i686-unknown-linux-musl.tar.gz
  restic: https://github.com/restic/restic/releases/download/v{{ versions.restic }}/restic_{{ versions.restic }}_linux_amd64.bz2
  rg: https://github.com/BurntSushi/ripgrep/releases/download/{{ versions.rg }}/ripgrep-{{ versions.rg }}-x86_64-unknown-linux-musl.tar.gz
  yq: https://github.com/mikefarah/yq/releases/download/{{ versions.yq }}/yq_linux_amd64.tar.gz
  ytop: https://github.com/cjbassi/ytop/releases/download/{{ versions.ytop }}/ytop-{{ versions.ytop }}-x86_64-unknown-linux-gnu.tar.gz
  zoxide: https://github.com/ajeetdsouza/zoxide/releases/download/v{{ versions.zoxide }}/zoxide-{{ versions.zoxide }}-x86_64-unknown-linux-musl.tar.gz
  task: https://github.com/go-task/task/releases/download/{{ versions.task }}/task_linux_amd64.tar.gz
  mcfly_enabled: true
