- name: Bat
  ansible.builtin.include_tasks: bat.yaml
- name: Cosign
  ansible.builtin.include_tasks: cosign.yaml
- name: Dive
  ansible.builtin.include_tasks: dive.yaml
- name: Fd
  ansible.builtin.include_tasks: fd.yaml
- name: Fzf
  ansible.builtin.include_tasks: fzf.yaml
- name: Gomplate
  ansible.builtin.include_tasks: gomplate.yaml
- name: Goreleaser
  ansible.builtin.include_tasks: goreleaser.yaml
- name: Hadolint
  ansible.builtin.include_tasks: hadolint.yaml
- name: Lazydocker
  ansible.builtin.include_tasks: lazydocker.yaml
- name: Lazygit
  ansible.builtin.include_tasks: lazygit.yaml
- name: McFly
  ansible.builtin.include_tasks: mcfly.yaml
- name: Ripgrep
  ansible.builtin.include_tasks: rg.yaml
- name: Restic
  ansible.builtin.include_tasks: restic.yaml
- name: Task
  ansible.builtin.include_tasks: task.yaml
- name: Yq
  ansible.builtin.include_tasks: yq.yaml
- name: Ytop
  ansible.builtin.include_tasks: ytop.yaml
- name: Zoxide
  ansible.builtin.include_tasks: zoxide.yaml
