copacetic:
  # renovate: datasource=github-releases depName="project-copacetic/copacetic"
  version: 0.10.0
helm:
  # renovate: datasource=github-releases depName="helm/helm"
  version: v3.19.0
k9s:
  # renovate: datasource=github-releases depName="derailed/k9s"
  version: v0.50.16
kapp:
  # renovate: datasource=github-releases depName="carvel-dev/kapp"
  version: v0.64.2
krew:
  # renovate: datasource=github-releases depName="kubernetes-sigs/krew"
  version: v0.4.5
kubeconform:
  # renovate: datasource=github-releases depName="yannh/kubeconform"
  version: v0.7.0
kubectl:
  # renovate: datasource=github-releases depName="kubernetes/kubernetes"
  version: v1.33.0
kubeswitch:
  # renovate: datasource=github-releases depName="danielfoehrKn/kubeswitch"
  version: 0.9.3
kubecolor:
  # renovate: datasource=github-releases depName="kubecolor/kubecolor"
  version: 0.5.1
myks:
  # renovate: datasource=github-releases depName="mykso/myks"
  version: 4.11.4
sops:
  # renovate: datasource=github-releases depName="getsops/sops"
  version: v3.10.2
stern:
  # renovate: datasource=github-releases depName="stern/stern"
  version: 1.32.0
trivy:
  # renovate: datasource=github-releases depName="aquasecurity/trivy"
  version: 0.62.1
vendir:
  # renovate: datasource=github-releases depName="carvel-dev/vendir"
  version: v0.44.0
ytt:
  # renovate: datasource=github-releases depName="carvel-dev/ytt"
  version: v0.52.1
crane:
  # renovate: datasource=github-releases depName="google/go-containerregistry"
  version: v0.20.6
